# Generated by Django 3.2.8 on 2021-10-29 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikeasset',
            fields=[
                ('need_repair', models.BooleanField(default=False)),
                ('status', models.BooleanField()),
                ('bike_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Bike assets',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
                ('customer_dob', models.DateField()),
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_email', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(max_length=12)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Depots',
            fields=[
                ('depot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depot_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiresession_id', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
                ('payment_id', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SessionPayment', to='bikecustomer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='paycred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycred_id', models.IntegerField()),
                ('paycred_type', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paycred', to='bikecustomer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Hiresession',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('start_depot', models.CharField(max_length=40)),
                ('end_depot', models.CharField(max_length=40)),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikecustomer.bikeasset')),
            ],
            options={
                'verbose_name_plural': 'Hire Session',
            },
        ),
        migrations.AddField(
            model_name='bikeasset',
            name='current_depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bikeasset', to='bikecustomer.depots'),
        ),
    ]
