# Generated by Django 3.2.1 on 2021-10-02 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
                ('dob', models.DateTimeField()),
                ('customer_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
