# Generated by Django 3.2.1 on 2021-10-02 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikecustomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_condition', models.IntegerField()),
                ('current_depot', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('bike_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Bike assets',
            },
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='dob',
            new_name='customer_dob',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='customer_phone',
        ),
    ]
