# Generated by Django 3.2.8 on 2021-11-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikecustomer', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycred',
            name='id',
        ),
        migrations.AlterField(
            model_name='paycred',
            name='paycred_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
