# Generated by Django 3.2.1 on 2021-10-06 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikecustomer', '0003_hiresession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot_id', models.IntegerField()),
                ('depot_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='paycred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycred_id', models.IntegerField()),
                ('paycred_type', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiresession_id', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
                ('payment_id', models.IntegerField()),
                ('customer_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bikes',
            new_name='Bikeasset',
        ),
    ]
