# Generated by Django 3.2.8 on 2021-10-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikecustomer', '0005_auto_20211029_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiresession',
            name='end_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
