# Generated by Django 3.2.8 on 2021-10-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikecustomer', '0006_alter_hiresession_end_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiresession',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
