# Generated by Django 3.2.8 on 2021-10-29 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikecustomer', '0007_alter_hiresession_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiresession',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='hiresession',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
